language: c

compiler:
  - gcc
  - clang

script: ./bootstrap-configure && make

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libopenconnect-dev openconnect openvpn vpnc
  - sudo apt-get install libdbus-1-dev
  - sudo apt-get install iptables-dev
