# SPDX-License-Identifier: MIT

language: c

compiler:
  - gcc

matrix:
  include:
    - os: linux
      before_install:
        - docker pull debian:latest
        - docker run --name travis-ci -v $TRAVIS_BUILD_DIR:/travis -w /travis -td debian:latest /bin/bash
      install:
        - docker exec -ti travis-ci bash -c "apt-get update"
        - docker exec -ti travis-ci bash -c "apt-get install -y build-essential autoconf automake aclocal libtool libudev-dev libglib2.0-dev libdbus-1-dev gtk-doc-tools libgnutls28-dev libreadline-dev libxtables-dev  wpasupplicant libbluetooth-dev ppp-dev"
    - os: linux
      before_install:
        - docker pull debian:testing
        - docker run --name travis-ci -v $TRAVIS_BUILD_DIR:/travis -w /travis -td debian:testing /bin/bash
      install:
        - docker exec -ti travis-ci bash -c "apt-get update"
        - docker exec -ti travis-ci bash -c "apt-get install -y build-essential autoconf automake aclocal libtool libudev-dev libglib2.0-dev libdbus-1-dev gtk-doc-tools libgnutls28-dev libreadline-dev libxtables-dev  wpasupplicant libbluetooth-dev ppp-dev"
    - os: linux
      before_install:
        - docker pull fedora:latest
        - docker run --name travis-ci -v $TRAVIS_BUILD_DIR:/travis -w /travis -td fedora:latest /bin/bash
      install:
        - docker exec -ti travis-ci bash -c "dnf -y update"
        - docker exec -ti travis-ci bash -c "dnf -y install @development-tool autoconf automake libtool glib2-devel dbus-devel iptables-devel gnutls-devel readline-devel"

script:
  - docker exec -ti travis-ci bash -c "./bootstrap-configure && ./configure && make"

after_script:
- docker stop travis-ci
